# Tutorial mixture: 20% fat, 70% water, 10% collagen by mass.
/det/setComp0 0.20
/det/setComp1 0.70
/det/setComp2 0.10
/det/setComp3 0.00
/det/setPhantomMaterial 2
/det/setPhantomDiameter 10. mm
/det/setPhantomHeight 1. mm
/det/setPhantomZ 500. mm
/det/setSlits false
/det/setDetectorSize 300. mm
/det/setDetectorThickness 1. mm
/det/setDetectorSampleDistance 500. mm
/phys/SelectPhysicsList empenelopeMI
/run/setCut 0.1 mm
/run/verbose 1
/run/initialize
/run/setfilenamesave results/builtin_mix_20_70_10
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/radius 0.1 mm
/gps/pos/centre 0. 0. 0. mm
/gps/direction 0 0 1
/gps/particle gamma
/gps/ene/type Mono
/gps/ene/mono 20. keV
/run/printProgress 50000
/run/beamOn 200000
