# 100k-event geometry and scoring validation.
/random/setSeeds 161803 141421
/det/setCustomMatDensity 0.9794738076
/det/setCustomMatHmassfract 0.1074785105
/det/setCustomMatCmassfract 0.4680700880
/det/setCustomMatNmassfract 0.0189646254
/det/setCustomMatOmassfract 0.4054867761
/det/SetCustomMatFF data/keele_breast_g50.dat
/det/setPhantomMaterial 30
/det/setPhantomBox true
/det/setPhantomDiameter 50. mm
/det/setPhantomHeight 60. mm
/det/setPhantomZ 100. mm
/det/setSlits false
/det/setDetectorSize 70.710678 mm
/det/setDetectorThickness 0.3 mm
/det/setDetectorSampleDistance 175.15 mm
/phys/SelectPhysicsList empenelopeMI
/run/setCut 0.01 mm
/run/verbose 1
/run/initialize
/run/setfilenamesave results/keele_breast_g50_pilot
/sd/setSK true
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. mm
/gps/direction 0 0 1
/gps/particle gamma
/gps/ene/type Mono
/gps/ene/mono 22.162917 keV
/run/printProgress 10000
/run/beamOn 100000
